### ISSUE TITLE
Doesn't seem to work at all for me

### ISSUE THREAD

**Issue by watkins** [takac/vim-spotifysearch#20]
Tried the example:
`:Spotify yeezus`
and got
`No tracks could be found`

Then I tried
`:Spotify everlong`
and again got
`No tracks could be found`

It seems no matter what I try it doesn't work

**Comment by takac** [comment]
I reckon the API is now turned off. It has been derprecated for a while and there is a new one to consume. It will be a lot of work to update.

**Comment by watkins** [comment]
By 

> new one to consume

I presume you mean [this one](https://developer.spotify.com/web-api/ ) that you mentioned in #18?

**Comment by takac** [comment]
Yes. Maybe when I have a spare couple weeks I'll have a go :)

**Comment by watkins** [comment]
Okay, I might have a look into it and help you out if I get time (although I have no past experience with spotify APIs so idk how much use I would be)

**Comment by takac** [comment]
I've pushed a fix which used 'spotipy'. You will need to `pip install spotipy` and have vim compile with python support (which is a typical default).

**Comment by watkins** [comment]
Thanks. For some reason (probably something on my end) this still isn't working however...

I tried installing spotipy with the command `pip install spotipy` and first got a permission error and so ran it with sudo.

After installing spotipy, I updated my version of this plugin with :BundleUpdate (I'm using vundle), closed and reopened vim and tried: `:Spotify everlong`

This [gave me an error](https://i.gyazo.com/50847919f56603b164722cccb4290ffd.png) (likely due to spotipy not being installed or vim not compiling with python support as you mentioned):

> Error detected while processing function SpotifyTrackSearch:
> line   14:
> Traceback (most recent call last):
>   File "<string>", line 7, in <module>
> AttributeError: 'module' object has no attribute 'Dictionary'
> line   15:
> E121: Undefined variable: g:tracks
> E15: Invalid expression: g:tracks
> line   17:
> E716: Key not present in Dictionary: everlong
> E15: Invalid expression: s:cache.track_search[a:track]
> line   18:
> E121: Undefined variable: tracks
> E116: Invalid arguments for function len(tracks['tracks']['items']) == 0
> E15: Invalid expression: len(tracks['tracks']['items']) == 0
> line   24:
> E121: Undefined variable: tracks
> E116: Invalid arguments for function <SNR>43_PrintTracks

I pressed return and got 'spotify_list[-]' but empty: https://i.gyazo.com/a7328aa4172f38383e5ef477d694eb48.png

**Comment by takac** [comment]
What version of Vim are you running? `module' object has no attribute 'Dictionary'` is refering to the `vim` module which should have a dictionary object.

**Comment by watkins** [comment]
I'm running version 7.3:

`VIM - Vi IMproved 7.3 (2010 Aug 15, compiled Jul  9 2015 23:58:42)                            │        modified:   app/views/devise/registrations/new.html.erb
Compiled by root@apple.com                                                                    │        modified:   app/views/devise/sessions/new.html.erb
Normal version without GUI.  Features included (+) or not (-):                                │        modified:   app/views/layouts/application.html.haml
-arabic +autocmd -balloon_eval -browse +builtin_terms +byte_offset +cindent                   │        modified:   config/initializers/devise.rb
-clientserver -clipboard +cmdline_compl +cmdline_hist +cmdline_info +comments                 │        modified:   db/schema.rb
-conceal +cryptv +cscope +cursorbind +cursorshape +dialog_con +diff +digraphs                 │
-dnd -ebcdic -emacs_tags +eval +ex_extra +extra_search -farsi +file_in_path                   │Untracked files:
+find_in_path +float +folding -footer +fork() -gettext -hangul_input +iconv                   │  (use "git add <file>..." to include in what will be committed)
+insert_expand +jumplist -keymap -langmap +libcall +linebreak +lispindent                     │
+listcmds +localmap -lua +menu +mksession +modify_fname +mouse -mouseshape                    │        db/migrate/20160526202314_add_subject_id_to_student.rb
-mouse_dec -mouse_gpm -mouse_jsbterm -mouse_netterm -mouse_sysmouse                           │        db/migrate/20160526202611_add_student_id_to_subject.rb
+mouse_xterm +multi_byte +multi_lang -mzscheme +netbeans_intg -osfiletype                     │        db/migrate/20160527193518_add_username_to_students.rb
+path_extra -perl +persistent_undo +postscript +printer -profile +python/dyn                  │        db/migrate/20160527193941_remove_subject_id_from_student.rb
-python3 +quickfix +reltime -rightleft +ruby/dyn +scrollbind +signs                           │
+smartindent -sniff +startuptime +statusline -sun_workshop +syntax +tag_binary                │no changes added to commit (use "git add" and/or "git commit -a")
+tag_old_static -tag_any_white -tcl +terminfo +termresponse +textobjects +title               │➜  revisionHub git:(master) ✗ 
 -toolbar +user_commands +vertsplit +virtualedit +visual +visualextra +viminfo                │
+vreplace +wildignore +wildmenu +windows +writebackup -X11 -xfontset -xim -xsmp               │
 -xterm_clipboard -xterm_save                                                                 │
   system vimrc file: "$VIM/vimrc"                                                            │
     user vimrc file: "$HOME/.vimrc"                                                          │
      user exrc file: "$HOME/.exrc"                                                           │
  fall-back for $VIM: "/usr/share/vim"                                                        │
Compilation: gcc -c -I. -D_FORTIFY_SOURCE=0 -Iproto -DHAVE_CONFIG_H -arch i386 -arch x86_64 -g│
 -Os -pipe                                                                                    │
Linking: gcc -arch i386 -arch x86_64 -o vim -lncurses  `

**Comment by watkins** [comment]
Just updated to version 7.4 and it's working now
